web:
 image: nginx:latest
 ports:
  - "10001:80"
  - "5001:8080"
 volumes:
  - ./code:/code:z
  - ./site.conf:/etc/nginx/conf.d/default.conf:z
 links:
  - php
php:
 image: php:7-fpm
 volumes:
  - ./lib/Smarty-3.1.30:/usr/local/lib/Smarty-3.1.30:z
  - ./smarty.ini:/usr/local/etc/php/conf.d/smarty.ini:z
  - ./code:/code:z

mysqldb:
    image: mysql
    container_name: ${MYSQL_HOST}
    restart: always
    environment:
        - MYSQL_DATABASE=article_repository
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=user
        - MYSQL_PASSWORD=toor
    ports:
        - "8989:3306"
    volumes:
        - ./data/db/mysql:/var/lib/mysql:z
