version: '3'

services:
 web:
  image: nginx:latest
  ports:
   - "10001:80"
   - "5001:8080"
  volumes:
   - ./code:/code:z
   - ./site.conf:/etc/nginx/conf.d/default.conf:z
  links:
   - php

 php:
  build:
   context: ./dockerfiles
   dockerfile: php.Dockerfile
  volumes:
   - ./lib/Smarty-3.1.30:/usr/local/lib/Smarty-3.1.30:z
   - ./smarty.ini:/usr/local/etc/php/conf.d/smarty.ini:z
   - ./code:/code:z
  links:
   - mysqldb

 mysqldb:
  image:    mysql
  container_name: database_host
  restart:  always
  environment:
   - MYSQL_DATABASE=article_repository
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=user
   - MYSQL_PASSWORD=toor
  ports:
   - "8989:3306"
  volumes:
   - ./data/db/mysql:/var/lib/mysql/:z

 composer:
   restart:    'no'
   image:   composer/composer:php7
   command:    dumpautoload -o
   working_dir:   /code
   volumes:
    - ./code:/code:z
